const mongoose = require("mongoose");

const videoVariantSchema = new mongoose.Schema(
  {
    resolution: {
      type: String,
      enum: ["1080p", "720p", "480p", "original"],
      default: "original"
    },
    url: {
      type: String,
      default: "",
      trim: true,
      maxlength: 2000
    },
    mimeType: {
      type: String,
      default: "video/mp4",
      trim: true
    },
    size: {
      type: Number,
      default: 0
    },
    bitrate: {
      type: Number,
      default: 0
    }
  },
  { _id: false }
);

const subtitleSchema = new mongoose.Schema(
  {
    lang: {
      type: String,
      default: "es-MX",
      trim: true
    },
    label: {
      type: String,
      default: "Español (México)",
      trim: true
    },
    url: {
      type: String,
      default: "",
      trim: true
    },
    autoGenerated: {
      type: Boolean,
      default: true
    },
    approved: {
      type: Boolean,
      default: false
    },
    vttContent: {
      type: String,
      default: "",
      trim: true
    }
  },
  { _id: false }
);

const mediaSchema = new mongoose.Schema(
  {
    url: {
      type: String,
      default: "",
      trim: true,
      maxlength: 2000
    },
    type: {
      type: String,
      enum: ["image", "video", ""],
      default: ""
    },
    mimeType: {
      type: String,
      default: "",
      trim: true
    },
    size: {
      type: Number,
      default: 0
    },
    alt: {
      type: String,
      default: "",
      trim: true,
      maxlength: 500
    },
    focalPoint: {
      x: { type: Number, min: 0, max: 1, default: 0.5 },
      y: { type: Number, min: 0, max: 1, default: 0.5 }
    },
    posterUrl: {
      type: String,
      default: "",
      trim: true,
      maxlength: 2000
    },
    width: {
      type: Number,
      default: 0
    },
    height: {
      type: Number,
      default: 0
    },
    orientation: {
      type: String,
      enum: ["vertical", "horizontal", "square", ""],
      default: ""
    },
    variants: {
      type: [videoVariantSchema],
      default: []
    },
    subtitles: {
      type: [subtitleSchema],
      default: []
    },
    processingStatus: {
      type: String,
      enum: ["pending", "processing", "completed", "failed", "ready"],
      default: "ready"
    },
    duration: {
      type: Number,
      default: 0
    },
    trim: {
      start: { type: Number, default: 0 },
      end: { type: Number, default: 0 },
      muted: { type: Boolean, default: false }
    }
  },
  { _id: false }
);

const carouselItemSchema = new mongoose.Schema(
  {
    url: {
      type: String,
      required: true,
      trim: true,
      maxlength: 2000
    },
    type: {
      type: String,
      enum: ["image"],
      default: "image"
    },
    mimeType: {
      type: String,
      default: "",
      trim: true
    },
    size: {
      type: Number,
      default: 0
    },
    alt: {
      type: String,
      default: "",
      trim: true,
      maxlength: 500
    }
  },
  { _id: false }
);

const lineageSchema = new mongoose.Schema(
  {
    derivedFrom: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Post",
      default: null
    },
    tool: {
      type: String,
      enum: ["remix", "kairos-image", "kairos-video", "kairos-script", ""],
      default: ""
    },
    aiGenerated: {
      type: Boolean,
      default: false
    }
  },
  { _id: false }
);

const pollOptionSchema = new mongoose.Schema(
  {
    text: {
      type: String,
      required: true,
      trim: true,
      maxlength: 120
    }
  },
  { _id: true }
);

const pollVoteSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true
    },
    optionId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true
    }
  },
  { _id: false }
);

const pollSchema = new mongoose.Schema(
  {
    question: {
      type: String,
      required: true,
      trim: true,
      maxlength: 200
    },
    options: {
      type: [pollOptionSchema],
      required: true,
      validate: {
        validator(items) {
          return Array.isArray(items) && items.length >= 2 && items.length <= 6;
        },
        message: "La encuesta debe tener entre 2 y 6 opciones"
      }
    },
    votes: {
      type: [pollVoteSchema],
      default: []
    },
    closesAt: {
      type: Date,
      default: null
    }
  },
  { _id: false }
);

const eventRsvpSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true
    },
    status: {
      type: String,
      enum: ["interested", "going"],
      required: true
    }
  },
  { _id: false }
);

const eventSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 160
    },
    description: {
      type: String,
      default: "",
      trim: true,
      maxlength: 1000
    },
    startsAt: {
      type: Date,
      required: true
    },
    endsAt: {
      type: Date,
      default: null
    },
    timezone: {
      type: String,
      default: "UTC",
      trim: true,
      maxlength: 64
    },
    locationType: {
      type: String,
      enum: ["online", "in_person"],
      default: "online"
    },
    location: {
      type: String,
      default: "",
      trim: true,
      maxlength: 300
    },
    rsvps: {
      type: [eventRsvpSchema],
      default: [],
      validate: {
        validator(items) {
          return Array.isArray(items) && items.length <= 50000;
        },
        message: "El evento alcanzó el máximo de confirmaciones"
      }
    }
  },
  { _id: false }
);

const REACTION_TYPES = ["like", "love", "laugh", "wow", "sad", "angry"];
const AUDIENCE_TYPES = ["public", "followers", "private", "circle", "orbit"];

const audienceSchema = new mongoose.Schema(
  {
    type: {
      type: String,
      enum: AUDIENCE_TYPES,
      default: "public",
      required: true
    },
    circleId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Circle",
      default: null
    },
    orbitId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Orbit",
      default: null
    }
  },
  { _id: false }
);

const reactionSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true
    },
    type: {
      type: String,
      enum: REACTION_TYPES,
      required: true
    }
  },
  { _id: false }
);

const postSchema = new mongoose.Schema(
  {
    content: {
      type: String,
      default: "",
      trim: true,
      maxlength: 5000
    },

    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true
    },

    // Legacy binary likes remain for backwards compatibility. New clients use
    // `reactions`; normalización y la ruta de compatibilidad los proyectan como
    // reacción `like` cuando no existe una reacción explícita.
    likes: {
      type: [
        {
          type: mongoose.Schema.Types.ObjectId,
          ref: "User"
        }
      ],
      default: [],
      validate: {
        validator(items) {
          return Array.isArray(items) && items.length <= 50000;
        },
        message: "La publicación alcanzó el máximo de likes"
      }
    },

    reactions: {
      type: [reactionSchema],
      default: [],
      validate: {
        validator(items) {
          return Array.isArray(items) && items.length <= 50000;
        },
        message: "La publicación alcanzó el máximo de reacciones"
      }
    },

    lineage: {
      type: lineageSchema,
      default: () => ({})
    },
    audience: {
      type: audienceSchema,
      default: () => ({ type: "public" })
    },

    poll: {
      type: pollSchema,
      default: null
    },

    event: {
      type: eventSchema,
      default: null
    },

    hashtags: {
      type: [
        {
          type: String,
          trim: true,
          lowercase: true,
          maxlength: 50
        }
      ],
      default: [],
      validate: {
        validator(tags) {
          return Array.isArray(tags) && tags.length <= 20;
        },
        message: "La publicación no puede superar 20 hashtags"
      }
    },

    comments: {
      type: [
        {
          user: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true
          },

          content: {
            type: String,
            required: true,
            trim: true,
            maxlength: 1000
          },

          parentComment: {
            type: mongoose.Schema.Types.ObjectId,
            default: null
          },

          createdAt: {
            type: Date,
            default: Date.now
          }
        }
      ],
      default: []
    },

    media: {
      type: mediaSchema,
      default: () => ({ url: "", type: "", mimeType: "", size: 0, alt: "" })
    },

    mediaItems: {
      type: [carouselItemSchema],
      default: [],
      validate: {
        validator(items) {
          return Array.isArray(items) && items.length <= 4;
        },
        message: "El carrusel no puede superar 4 imágenes"
      }
    },

    savedBy: {
      type: [
        {
          type: mongoose.Schema.Types.ObjectId,
          ref: "User"
        }
      ],
      default: []
    },

    repostOf: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Post",
      default: null
    },

    // KRONOS-UI-011 — moderación global (solo moderadores). Los posts
    // antiguos no tienen el subdocumento: se leen como no ocultos.
    moderation: {
      hidden: { type: Boolean, default: false, index: true },
      reason: { type: String, default: "", trim: true, maxlength: 500 },
      hiddenBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        default: null
      },
      hiddenAt: { type: Date, default: null }
    }
  },
  {
    timestamps: true,
    strict: true
  }
);

postSchema.index({
  author: 1,
  createdAt: -1
});

postSchema.index({
  createdAt: -1
});

const Post = mongoose.model("Post", postSchema);
Post.REACTION_TYPES = REACTION_TYPES;
Post.AUDIENCE_TYPES = AUDIENCE_TYPES;

module.exports = Post;
