import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import axios from "axios";
import { API_URL } from "../../services/apiClient";
import { getToken } from "../../services/authStorage";
const API = API_URL;
function token() { return getToken(); }
function auth() { const value = token(); return value ? { headers: { Authorization: `Bearer ${value}` } } : {}; }
export default function VideoGenerator() {
  const [prompt, setPrompt] = useState(""); const [videoUrl, setVideoUrl] = useState(""); const [status, setStatus] = useState(""); const [message, setMessage] = useState(""); const [history, setHistory] = useState([]); const [loading, setLoading] = useState(false);
  async function loadHistory() { try { const response = await axios.get(`${API}/ai/videos/history`, auth()); setHistory(Array.isArray(response.data?.generations) ? response.data.generations : []); } catch (error) { setMessage(error.response?.data?.error || "No se pudo cargar el historial de video."); } }
  async function generate(event) { event.preventDefault(); if (!prompt.trim() || loading) return; setLoading(true); setMessage(""); try { const response = await axios.post(`${API}/ai/videos/generate`, { prompt: prompt.trim() }, auth()); const generation = response.data?.generation; setStatus(generation?.status || "processing"); setVideoUrl(generation?.videoUrl || ""); setMessage(response.data?.message || "Kairos está procesando tu video."); loadHistory(); } catch (error) { setMessage(error.response?.data?.error || "Error generando video."); } finally { setLoading(false); } }
  useEffect(() => { loadHistory(); }, []);
  return <section className="page k-kairos-tool-page"><header className="k-page-header"><div><p className="k-eyebrow">KAIROS / VIDEO ENGINE</p><h1>Generar video</h1><p>Construye una escena audiovisual desde una dirección creativa.</p></div><Link className="k-button k-button-ghost" to="/kairos">Volver a Kairos</Link></header><form className="k-ai-form k-surface" onSubmit={generate}><label>Prompt<textarea value={prompt} onChange={event => setPrompt(event.target.value)} placeholder="Una secuencia cinematográfica de acero y lluvia..." required /></label><button className="k-button k-button-ai" type="submit" disabled={loading}>{loading ? "KAIROS procesando..." : "Generar video"}</button></form>{status && <p className="k-state" role="status">Estado: <strong>{status}</strong></p>}{message && <p className="k-state" role="status">{message}</p>}{videoUrl && <div className="k-ai-result k-card-ai"><video src={videoUrl} controls playsInline /></div>}<section className="k-history"><div className="k-section-heading"><h2>Historial de video</h2><span className="k-muted">{history.length} generaciones</span></div>{history.map(item => <article className="k-surface k-history-row" key={item._id}><strong>{item.status}</strong><span>{item.prompt}</span>{item.videoUrl && <button className="k-button k-button-secondary" type="button" onClick={() => { setVideoUrl(item.videoUrl); setStatus(item.status); }}>Ver video</button>}</article>)}</section></section>;
}
