import { useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../../services/apiClient";

export default function UserSearch() {
  const [query, setQuery] = useState(""); const [users, setUsers] = useState([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [actionUserId, setActionUserId] = useState("");
  async function search() { const value = query.trim(); if (!value) { setUsers([]); setError(""); return; } setLoading(true); setError(""); try { const { data } = await api.get("/users/search", { params: { q: value } }); setUsers(Array.isArray(data?.users) ? data.users : []); } catch (requestError) { setError(requestError.response?.data?.error || "No se pudieron buscar usuarios."); } finally { setLoading(false); } }
  async function toggleFollow(userId) { if (!userId || actionUserId) return; setActionUserId(userId); setError(""); try { const { data } = await api.post(`/users/${userId}/follow`); setUsers(items => items.map(user => user._id === userId ? { ...user, isFollowing: Boolean(data.following), followersCount: user.followersCount === null ? null : Math.max(0, (user.followersCount || 0) + (data.following ? 1 : -1)) } : user)); } catch (requestError) { setError(requestError.response?.data?.error || "No se pudo actualizar el seguimiento."); } finally { setActionUserId(""); } }
  function onKeyDown(event) { if (event.key === "Enter") { event.preventDefault(); search(); } }
  return <section className="page"><header className="k-page-header"><div><p className="k-eyebrow">KRONOS / DISCOVER</p><h1>Explorar personas</h1><p>Encuentra perfiles y conecta con tu comunidad.</p></div></header><div className="k-search-row"><input type="search" value={query} onChange={event => setQuery(event.target.value)} onKeyDown={onKeyDown} maxLength={50} placeholder="Buscar usuario..." aria-label="Buscar usuario" /><button className="k-button k-button-primary" type="button" onClick={search} disabled={loading || !query.trim()}>{loading ? "Buscando..." : "Buscar"}</button></div>{error && <p className="k-state k-state-error" role="alert">{error}</p>}{!loading && query.trim() && users.length === 0 && !error && <div className="k-empty-state"><h2>No encontramos perfiles</h2><p>Prueba con otro username o nombre visible.</p></div>}<div className="k-user-results">{users.map(user => <article className="k-surface k-user-result" key={user._id}><Link className="k-avatar k-avatar-lg" to={`/users/${user._id}`}>{user.displayName?.slice(0, 1) || user.username?.slice(0, 1) || "K"}</Link><div><Link to={`/users/${user._id}`}><strong>{user.displayName || user.username}</strong></Link><p>@{user.username}</p>{user.bio && <p>{user.bio}</p>}{user.followersCount !== null && <small>{user.followersCount || 0} seguidores</small>}</div><button className="k-button k-button-secondary" type="button" onClick={() => toggleFollow(user._id)} disabled={actionUserId === user._id}>{actionUserId === user._id ? "..." : user.isFollowing ? "Dejar de seguir" : "Seguir"}</button></article>)}</div></section>;
}
