import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import axios from "axios";
import { API_URL } from "../../services/apiClient";
import { getToken } from "../../services/authStorage";
const API = API_URL;
function auth() { const value = getToken(); return value ? { headers: { Authorization: `Bearer ${value}` } } : {}; }
export default function ImageGenerator() {
  const [prompt, setPrompt] = useState(""); const [negativePrompt, setNegativePrompt] = useState(""); const [style, setStyle] = useState("cinematic"); const [imageUrl, setImageUrl] = useState(""); const [history, setHistory] = useState([]); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  async function loadHistory() { try { const response = await axios.get(`${API}/ai/images/history`, auth()); setHistory(Array.isArray(response.data?.generations) ? response.data.generations : []); } catch (error) { setMessage(error.response?.data?.error || "No se pudo cargar el historial visual."); } }
  async function generate(event) { event.preventDefault(); if (!prompt.trim() || loading) return; setLoading(true); setMessage(""); try { const response = await axios.post(`${API}/ai/images/generate`, { prompt: prompt.trim(), negativePrompt, style }, auth()); setImageUrl(response.data?.url || response.data?.imageUrl || ""); setMessage(response.data?.message || "Generación completada."); loadHistory(); } catch (error) { setMessage(error.response?.data?.error || "Error generando imagen."); } finally { setLoading(false); } }
  useEffect(() => { loadHistory(); }, []);
  return <section className="page k-kairos-tool-page"><header className="k-page-header"><div><p className="k-eyebrow">KAIROS / IMAGE ENGINE</p><h1>Generar imagen</h1><p>Describe la dirección visual. Kairos se encarga del primer pase.</p></div><Link className="k-button k-button-ghost" to="/kairos">Volver a Kairos</Link></header><div className="k-ai-workspace"><form className="k-ai-form k-surface" onSubmit={generate}><label>Prompt<textarea value={prompt} onChange={event => setPrompt(event.target.value)} placeholder="Una ciudad de titanio bajo la lluvia..." required /></label><label>Negative prompt<textarea value={negativePrompt} onChange={event => setNegativePrompt(event.target.value)} placeholder="Elementos que quieres evitar" /></label><label>Estilo<select value={style} onChange={event => setStyle(event.target.value)}><option value="cinematic">Cinemático</option><option value="editorial">Editorial</option><option value="concept-art">Concept art</option><option value="photorealistic">Fotorrealista</option></select></label><button className="k-button k-button-ai" type="submit" disabled={loading}>{loading ? "KAIROS procesando..." : "Generar imagen"}</button></form><div className="k-ai-result k-card-ai">{imageUrl ? <img src={imageUrl} alt={prompt} /> : <div className="k-empty-state"><SparklesPlaceholder /><h2>Tu resultado aparecerá aquí</h2><p>Genera una imagen para iniciar.</p></div>}{message && <p className="k-state" role="status">{message}</p>}</div></div><section className="k-history"><div className="k-section-heading"><h2>Últimas generaciones</h2><Link to="/kairos/history">Ver todo</Link></div>{history.length === 0 ? <p className="k-muted">Todavía no hay generaciones.</p> : <div className="k-history-grid">{history.filter(item => item.imageUrl).map(item => <button className="k-history-item" key={item._id} type="button" onClick={() => setImageUrl(item.imageUrl)}><img src={item.imageUrl} alt={item.prompt} /></button>)}</div>}</section></section>;
}
function SparklesPlaceholder() { return <div className="k-kairos-placeholder" aria-hidden="true">✦</div>; }
