import { useEffect, useState } from "react";
import axios from "axios";
import { Link } from "react-router-dom";
import { API_URL } from "../../services/apiClient";
import { getToken } from "../../services/authStorage";
const API = API_URL;
function token() { return getToken(); }
function auth() { const value = token(); return value ? { headers: { Authorization: `Bearer ${value}` } } : {}; }
export default function ScriptGenerator() {
  const [prompt, setPrompt] = useState(""); const [type, setType] = useState("video"); const [tone, setTone] = useState(""); const [audience, setAudience] = useState(""); const [durationMinutes, setDurationMinutes] = useState(5); const [result, setResult] = useState(""); const [history, setHistory] = useState([]); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  async function loadHistory() { try { const response = await axios.get(`${API}/ai/scripts/history`, auth()); setHistory(Array.isArray(response.data?.scripts) ? response.data.scripts : []); } catch (error) { setMessage(error.response?.data?.error || "No se pudo cargar el historial de scripts."); } }
  async function generate(event) { event.preventDefault(); if (!prompt.trim() || loading) return; setLoading(true); setMessage(""); try { const response = await axios.post(`${API}/ai/scripts/generate`, { prompt: prompt.trim(), type, durationMinutes: Number(durationMinutes), tone, audience }, auth()); const script = response.data?.script; if (!script?.result) throw new Error("SCRIPT_INVALID_RESPONSE"); setResult(script.result); setMessage("Script generado correctamente."); loadHistory(); } catch (error) { setMessage(error.response?.data?.error || "Error generando script."); } finally { setLoading(false); } }
  useEffect(() => { loadHistory(); }, []);
  return <section className="page k-kairos-tool-page"><header className="k-page-header"><div><p className="k-eyebrow">KAIROS / SCRIPT ENGINE</p><h1>Generar script</h1><p>Da forma a una idea con estructura, tono y audiencia definidos.</p></div><Link className="k-button k-button-ghost" to="/kairos">Volver a Kairos</Link></header><form className="k-ai-form k-surface"><label>Tipo<select value={type} onChange={event => setType(event.target.value)}><option value="video">Video</option><option value="reel">Reel</option><option value="youtube">YouTube</option><option value="advertisement">Publicidad</option><option value="custom">Personalizado</option></select></label><label>Duración en minutos<input type="number" min="1" max="180" value={durationMinutes} onChange={event => setDurationMinutes(event.target.value)} /></label><label>Tono<input value={tone} onChange={event => setTone(event.target.value)} placeholder="Directo, cinematográfico..." /></label><label>Audiencia<input value={audience} onChange={event => setAudience(event.target.value)} placeholder="Para quién es" /></label><label>Prompt<textarea value={prompt} onChange={event => setPrompt(event.target.value)} placeholder="Escribe la idea central..." required /></label><button className="k-button k-button-ai" type="submit" onClick={generate} disabled={loading}>{loading ? "KAIROS procesando..." : "Generar script"}</button></form>{message && <p className="k-state" role="status">{message}</p>}{result && <article className="k-ai-result k-card-ai k-script-result"><pre>{result}</pre><button className="k-button k-button-secondary" type="button" onClick={() => navigator.clipboard.writeText(result)}>Copiar script</button></article>}<section className="k-history"><div className="k-section-heading"><h2>Historial de scripts</h2><span className="k-muted">{history.length} generaciones</span></div>{history.map(item => <button className="k-history-row k-surface" type="button" key={item._id} onClick={() => setResult(item.result)}><strong>{item.type}</strong><span>{item.prompt}</span></button>)}</section></section>;
}
